* améliorer l'UI avec des icones qui décrivent l'action quand on passe dessus
* refacto tiles call from column row
* add gridmap to service locator
* add score to service locator
* add level with vertical movements
* ajouter un buttonText qui se size automatiquement en fonction du texte et un button image
* create click button for full screen
* add sounds
* improve buttons look
* ajouter instruction level 3