* Créer 6 premiers niveaux
* add restart button to winscreen
* move win parameters
* améliorer l'UI avec des icones qui décrivent l'action quand on apsse dessus
* fixer le score systeme pour qu'on ne gagne une etoile que si le score total moyen a été améliorer, et pas seulement si on a dépassé le seuil sur cette etoile
* refacto tiles call from column row
* add gridmap to service locator
* add score to service locator
* debug ennemy shoot when they encounter another enemy